services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/.next
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - NEXT_TELEMETRY_DISABLED=1
      # Set the backend URL for server-side API routes
      - BACKEND_URL=http://backend:4000
      # Demo mode with fixed content for development/testing
      - USE_DEMO_CONTENT=false
    depends_on:
      - backend
    networks:
      - study-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    environment:
      - NODE_ENV=development
    networks:
      - study-network
    command: npm run dev

networks:
  study-network:
    driver: bridge
