services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: study-frontend:local
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - study-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: study-backend:local
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - NODE_ENV=development
    networks:
      - study-network

networks:
  study-network:
    driver: bridge
